d_prime: 2
beta: 100
N: 3
B: 100
num_samples_metrics: 1000
seed: 888
num_iterations: 50000
hidden_size: 128
num_layers: 6
optimizer:
  init_value: 0.0
  peak_value: 0.0003
  warmup_steps: 10000
  decay_steps: 40000
  end_value: 0.000001
